# Generated by Django 5.1.2 on 2024-11-14 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(choices=[('MR.', 'Mr.'), ('MRS.', 'Mrs.'), ('MISS.', 'Miss.')], default='', max_length=12)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=2)),
                ('address', models.TextField(help_text="Enter the patient's address here...")),
                ('department', models.CharField(choices=[('CLINICAL_MEDICINE', 'Clinical Medicine'), ('MICROBIOLOGY', 'Microbiology'), ('PATHOLOGY', 'Pathology'), ('IMMUNOLOGY', 'Immunology'), ('MOLECULAR_BIOLOGY', 'Molecular Biology'), ('BIOCHEMISTRY', 'Biochemistry')], default='CLINICAL_MEDICINE', max_length=50)),
                ('symptoms', models.TextField(help_text='Write about your concerns')),
                ('consultation_type', models.CharField(choices=[('OPD', 'OPD'), ('FOLLOW_UP', 'Follow Up')], default='OPD', max_length=20)),
                ('appointment_date_time', models.DateTimeField(help_text='Select the appointment date and time')),
                ('registration_date_time', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.state')),
            ],
        ),
    ]
