# Generated by Django 5.1.2 on 2024-11-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patientregistration_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='aadhar_number',
            field=models.BigIntegerField(blank=True, max_length=12, null=True),
        ),
    ]
