# Generated by Django 5.1.2 on 2024-11-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_patientregistration_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='aadhar_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
