# Generated by Django 5.1.2 on 2024-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patientregistration_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='appointment_date_time',
            field=models.DateField(help_text='Select the appointment date and time'),
        ),
    ]
