# Generated by Django 5.1.2 on 2024-11-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_patientregistration_appointment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientregistration',
            old_name='appointment_date_time',
            new_name='appointment_date',
        ),
    ]
