# Generated by Django 5.1.2 on 2024-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_appointment_date_time_patientregistration_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Write about your concerns', null=True),
        ),
    ]
