# Generated by Django 5.1.2 on 2024-11-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_first_name_patientregistration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='state',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.state'),
        ),
    ]
