# Generated by Django 5.1.2 on 2024-11-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_patientregistration_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientregistration',
            name='initial',
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.state'),
        ),
    ]
