# Generated by Django 5.1.2 on 2024-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_patientregistration_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='age',
            field=models.IntegerField(),
        ),
    ]
